### ISSUE TITLE
Add Basic HTML Canvas Infrastructure and Management Engine

### ISSUE THREAD

**Issue by S-A-R-C** [S-A-R-C/GameToolkit.js#1]
# GameToolkit.js Project Task

## Description

To properly display the game, introduce a background and foreground canvas with a canvas engine to manage them. Additionally, implement the main engine that I will start the initialization of the canvas engine using data located in the configuration engine.

## Subtasks

- [x] Add a HTML foreground canvas
- [x] Add a HTML background canvas
- [x] Add a JavaScript config engine
- [x] Add a JavaScript canvas engine
- [x] Add a JavaScript main engine
- [x] Add a main initialization phase

## Authors

* Gabriel Roy - Repository Owner - [S-A-R-C](https://github.com/S-A-R-C)
