### ISSUE TITLE
Insert New HTML Mangement Engine

### ISSUE THREAD

**Issue by S-A-R-C** [S-A-R-C/GameToolkit.js#10]
# GameToolkit.js Project Task

## Description

To get a better grasp on the HTML infrastructure that will be put in place in the near future, add a new HTML engine. Additionally, modify the existing codebase to take advantages of the newly introduced functionalities. However, the engine will be fleshed-out in future releases when required.

## Subtasks

- [ ] Create a new JavaScript HTML engine
- [ ] Add standard HTML management functions
- [ ] Modify existing codebase to use engine

## Authors

* Gabriel Roy - Repository Owner - [S-A-R-C](https://github.com/S-A-R-C)
