### ISSUE TITLE
Introduce Game Rendering Engine and Loop

### ISSUE THREAD

**Issue by S-A-R-C** [S-A-R-C/GameToolkit.js#3]
# GameToolkit.js Project Task

## Description

To display the game's content on the canvases, implement a rendering engine to control what is being shown on the screen as well as a rendering loop. While there isn't much to be displayed, for now, ensure the background canvas is at least colored.

## Subtasks

- [x] Add new JavaScript rendering engine
- [x] Add function to color submitted canvas
- [ ] Add function to clear content from canvas
- [x] Initiailize rendering loop in main engine

## Authors

* Gabriel Roy - Repository Owner - [S-A-R-C](https://github.com/S-A-R-C)
