### ISSUE TITLE
Resize Canvas When the Browser Window's Size Changes

### ISSUE THREAD

**Issue by S-A-R-C** [S-A-R-C/GameToolkit.js#5]
# GameToolkit.js Project Task

## Description

To keep the size of all the canvases consistent with the browser's size, measure the size of the browser on each refresh. If the size was found to have changed, resize all the game's canvases.

## Subtasks

- [x] Insert function to resize game's canvases
- [x] Initiate canvas resize during refresh phase
- [x] Resize only when window's size changed

## Authors

* Gabriel Roy - Repository Owner - [S-A-R-C](https://github.com/S-A-R-C)
