### ISSUE TITLE
Include a Logging Engine and Affix Logging to Codebase

### ISSUE THREAD

**Issue by S-A-R-C** [S-A-R-C/GameToolkit.js#7]
# GameToolkit.js Project Task

## Description

To ease future debugging sessions, add a new logging engine and affix logging that will be both displayed in the browser's console log and stored internally in an array. To standardized this component, add severity levels and timestamps to each line. Finally, configure the engine so that logging can be disabled via a configuration value.

## Subtasks

- [x] Add a new JavaScript logging engine
- [x] Add logging configuration values
- [x] Add logging to current codebase
- [x] Add readable timestamp to each log
- [x] Add a "FATAL" log severity level
- [x] Add an "ERROR" log severity level
- [x] Add a "WARN" log severity level
- [x] Add an "INFO" log severity level
- [x] Add a "DEBUG" log severity level
- [x] Add a "TRACE" log severity level

## Authors

* Gabriel Roy - Repository Owner - [S-A-R-C](https://github.com/S-A-R-C)
